# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add2 <- function(a, b) {
    .Call('_sim_add2', PACKAGE = 'sim', a, b)
}

compute_pi_c <- function(n) {
    .Call('_sim_compute_pi_c', PACKAGE = 'sim', n)
}

my_sum1 <- function(x) {
    .Call('_sim_my_sum1', PACKAGE = 'sim', x)
}

my_sum2 <- function(x) {
    .Call('_sim_my_sum2', PACKAGE = 'sim', x)
}

